### ISSUE TITLE
Opensource datasets

### ISSUE THREAD

**Issue by Tortoise17** [sign-language-processing/signbank-plus#8]
Dear Respected Friends, I have seen this repo very useful and really interesting. I want to ask that is there any opensource datasets available monolingual and multi-lingual sign language for different languages. 

Please if you could guide me that the dataset I could use for training. This would be a great help.

**Comment by AmitMY** [comment]
This repository is for a dataset for multilingual sign language translation, with SignWriting.
Here's a script to train an example model https://github.com/sign-language-processing/signbank-plus/blob/main/signbank_plus/nmt/sockeye/train.sh

If you want other datasets, see https://research.sign.mt/#list-of-datasets and https://github.com/sign-language-processing/datasets
